### ISSUE TITLE
Status of the project

### ISSUE THREAD

**Issue by fredwilliam** [kunkku/django-financial-accounting#1]
Hi, whats the status of this project?
Is it complete? incomplete, tested? How can i get information on how to use it?
i would appriciate your response so that i can use it
thanks

**Comment by kunkku** [comment]
I am using it for managing the accounts of my small consulting company. It is pretty all right for this use case, and it could be used as a basis for building higher-level business applications.

I added a small README file to explain how you can try it. Please let me know if you need more information. To make it easier to install, I plan to publish this project on PyPI later.

**Comment by fredwilliam** [comment]
This is great work, i have checked it and will use it. Thank you very much for sharing.
