### ISSUE TITLE
Need help to quick start

### ISSUE THREAD

**Issue by onclefranck** [kunkku/django-financial-accounting#3]
> After these steps, you are ready to start entering transactions to the ledger

It appears to be exactly what I need for my project. However, I need a little push to better start using your application properly.

Given there is a Journal created and a couple of Accounts, can you provide a snippet as of how do we should record a new transaction?

Thanks in advance

**Comment by kunkku** [comment]
I updated the documentation, adding a sample chart of accounts and a code snippet on recording a transaction. Please let me know if you need more information.

**Comment by onclefranck** [comment]
Many thanks, exactly what I expected. Regards.
